apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    url: timescaledb:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: market_data
      sslmode: disable
      timescaledb: true
      postgresVersion: 1400
      timezone: UTC
      timeInterval: "1m"
    isDefault: true
